config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Categories
  resources :categories
  get 'categorias' => 'categories#show_all', as: 'categories_show_all'

# Subcategories
  resources :subcategories
  get 'subcategorias/:id' => 'subcategories#show_all', as: 'subcategories_show_all'
  get 'subcategoria/:id' => 'subcategories#sub_posts', as: 'sub_posts'

# Managements
  get 'managements/index' => 'managements#index', as: 'managements_index'

# Pages
  root 'pages#home', as: 'home'
  get 'about' => 'pages#about', as: 'about'

# Posts
  post 'resultado-da-busca' => 'posts#search_posts', as: 'search_posts'
  resources :posts, param: :url

# Users
  get 'register' => 'users#new', as: 'register'
  get 'perfil' => 'users#show', as: 'perfil'
  patch 'update_password' => 'users#update_password'
  patch 'user_destroy' => 'users#destroy'
  post 'users/create' => 'users#create'
  get 'users/destroy'

# Sessions
  get 'admin_login' => 'sessions#new', as: 'login'
  post 'admin_login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/views/navbar/_navbar.html.erb
<nav>
	<div class="nav-fostrap">
		<ul>
			<li> <%= link_to 'HOME', home_path, class: 'nav-fostrap-link' %> </li>
			<li> <%= link_to 'POSTS', posts_path, class: 'nav-fostrap-link' %> </li>
			<li> <%= link_to 'CATEGORIAS', categories_show_all_path, class: 'nav-fostrap-link' %> </li>
			<li> <%= link_to 'SOBRE NÓS', about_path, class: 'nav-fostrap-link' %> </li>
			<% if logged_in? %>
				Bem vindo: <%= current_user.name %>
				<li> <%= link_to 'Painel', managements_index_path, class: 'nav-fostrap-link' %> </li>
				<li> <%= link_to 'Account', perfil_path, class: 'nav-fostrap-link' %> </li>
				<li> <%= link_to 'Sair', logout_path, class: 'nav-fostrap-link' %> </li>
			<% end %>
		</ul>
	</div>
	<div class="nav-bg-fostrap">
		<div class="navbar-fostrap"> 
			<span style="background-color: #03A9F4"></span style="background-color: #03A9F4"> <span style="background-color: #03A9F4"></span> <span style="background-color: #03A9F4"></span> 
		</div>
		<a class="title-mobile">APRENDE SIM</a>
</div>
</nav>
<div class='content'></div></div></div>
<script>
	$(document).ready(function(){
		$('.navbar-fostrap').click(function(){
			$('.nav-fostrap').toggleClass('visible');
			$('body').toggleClass('cover-bg');
		});
	});
</script>

app/views/navbar/_navbar_vertical.html.erb
<div class="navbar-toggle-button" id="navbar-toggle">
  <div class="one"></div>
  <div class="two"></div>
  <div class="three"></div>
</div>
<nav class="vertical-menu" id="menu">
   <%= image_tag "lucas-cut.png", class: "profile-image" %>

  <div class="vertical-menu-links">
    <%= link_to '<i class="fa fa-home"></i>'.html_safe, home_path, title: 'Home' %>
    <%= link_to '<i class="fa fa-file"></i>'.html_safe, posts_path, title: 'Posts' %>
    <%= link_to '<i class="fa fa-user"></i>'.html_safe, about_path, title: 'Perfil' %>
  </div>

  <div class="navbar-containers">
    <div class="navbar-categories">
      <%= link_to '<i class="fa fa-folder navbar-posts-folder"></i> Categorias <i class="fa fa-plus-circle"></i>'.html_safe, categories_show_all_path, title: 'Categorias' %>
    </div>
    <div onclick="togglePosts()" class="dropbtn navbar-posts">
      <i class="fa fa-folder navbar-posts-folder"></i> Posts <i class="fa fa-angle-down"></i>
    </div>
    <div id="myDropdown" class="dropdown-content">
      <% navbar_posts.each do |post| %> 
        <div class="dropdown-element">
          <%= image_tag subcategory_icon(post.subcategory_id), class: 'post-icon' %>
          <%= link_to post.title, post_path(post) %>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<script type="text/javascript">
// toggle for vertical navbar
$("#navbar-toggle").click(function() {
  $(this).toggleClass("on");
  $("#menu").animate({width: 'toggle'});
  if($(".body-container").css("opacity") == "1") {
    $(".body-container").css("opacity", "0.1");
  }
  else {
   $(".body-container").css("opacity", "1");
  }
});
</script>