config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Categories
  resources :categories
  get 'categorias' => 'categories#show_all', as: 'categories_show_all'

# Subcategories
  resources :subcategories
  get 'subcategorias/:id' => 'subcategories#show_all', as: 'subcategories_show_all'
  get 'subcategoria/:id' => 'subcategories#sub_posts', as: 'sub_posts'

# Managements
  get 'managements/index' => 'managements#index', as: 'managements_index'

# Pages
  root 'pages#home', as: 'home'
  get 'about' => 'pages#about', as: 'about'

# Posts
  post 'resultado-da-busca' => 'posts#search_posts', as: 'search_posts'
  resources :posts, param: :url

# Users
  get 'register' => 'users#new', as: 'register'
  get 'perfil' => 'users#show', as: 'perfil'
  patch 'update_password' => 'users#update_password'
  patch 'user_destroy' => 'users#destroy'
  post 'users/create' => 'users#create'
  get 'users/destroy'

# Sessions
  get 'admin_login' => 'sessions#new', as: 'login'
  post 'admin_login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord

  belongs_to :category
  has_many :posts

  validates :name, 
    presence: {message: 'O nome é obrigatório'},
    uniqueness: {message: 'Já exite uma Categoria com esse nome'}

end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]
  before_action :check_log_in, except: [:show_all, :sub_posts]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  def show_all
    @category = Category.find(params[:id])
    @subcategories = Subcategory.where(category_id: @category.id)
  end

  def sub_posts
    @subcategory = Subcategory.find(params[:id])
    @posts = Post.where(subcategory_id: @subcategory.id).order("created_at DESC")
    @categories = Category.all.order(:name)
    @posts_most_views = Post.all.order(:visits).limit(15)
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_log_in
      if logged_in? == false
        redirect_to home_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :icon, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory, local: true) do |form| %>
  <% if subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subcategory_name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon, id: :subcategory_icon %>
  </div>

  </br>
  <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]} %>
  </br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.icon %></td>
        <td><%= subcategory.category.name %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @subcategory.icon %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show_all.html.erb
<h1 class="categories-title">Subcategorias</h1>
<div class="category-group-container">
	<% @subcategories.each do |subcategory| %>
		<div class="category-single-container">
			<%= link_to subcategory.name, sub_posts_path(subcategory), class: 'category-name' %>
		</div>
	<% end %>
</div>

app/views/subcategories/sub_posts.html.erb
<h1 class="posts-index-title"> Subcategoria <%= @subcategory.name %> </h1>

<%= render "posts/posts_all" %>