config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# Categories
  resources :categories
  get 'categorias' => 'categories#show_all', as: 'categories_show_all'

# Subcategories
  resources :subcategories
  get 'subcategorias/:id' => 'subcategories#show_all', as: 'subcategories_show_all'
  get 'subcategoria/:id' => 'subcategories#sub_posts', as: 'sub_posts'

# Managements
  get 'managements/index' => 'managements#index', as: 'managements_index'

# Pages
  root 'pages#home', as: 'home'
  get 'about' => 'pages#about', as: 'about'

# Posts
  post 'resultado-da-busca' => 'posts#search_posts', as: 'search_posts'
  resources :posts, param: :url

# Users
  get 'register' => 'users#new', as: 'register'
  get 'perfil' => 'users#show', as: 'perfil'
  patch 'update_password' => 'users#update_password'
  patch 'user_destroy' => 'users#destroy'
  post 'users/create' => 'users#create'
  get 'users/destroy'

# Sessions
  get 'admin_login' => 'sessions#new', as: 'login'
  post 'admin_login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ApplicationRecord

  has_one :category
  has_one :subcategory
  has_one :author
  has_many :comments

  def to_param
    url
  end

  def increment()
    self.visits ||= 0
    self.visits += 1
    self.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_log_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").limit(10)
    @categories = Category.all.order(:name).limit(10)
    @posts_most_views = Post.all.order("visits DESC").limit(15)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_comments = Comment.where(post_id: @post.id)
    @author = Author.find_by(id: @post.author_id)
    @category = Category.find_by(id: @post.category_id)
    @subcategory = Subcategory.find_by(id: @post.subcategory_id)
    @categories = Category.all.order(:name)
    @posts_most_views = Post.all.order("visits DESC").limit(15)
    @comment = Comment.new
    @post.increment
  end

  # GET /posts/new
  def new
    @subcategories = Subcategory.all.order(:name)
    @categories = Category.all.order(:name)
    @authors = Author.all.order(:name)
    @post = Post.new
    @body_value = '<h2 class="post-text-h2"> </h2> <h3 class="post-text-h3"> </h3> <p class="post-text-p"> </p>'
  end

  # GET /posts/1/edit
  def edit
    @subcategories = Subcategory.all.order(:name)
    @categories = Category.all.order(:name)
    @authors = Author.all.order(:name)
    @body_value = @post.body
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_posts
    @search_param = params[:current_search][:search]
    @posts = Post.where("title ILIKE :search", 
      :search => "%#{params[:current_search][:search]}%")
    @categories = Category.all.order(:name).limit(10)
    @posts_most_views = Post.all.order("visits DESC").limit(15)
  end

  private
    def check_log_in
      if logged_in? == false
        redirect_to home_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(url: params[:url])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :body, :intro_text, 
        :front_image, :image_name, :category_id, :subcategory_id, :author_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def navbar_posts
    @posts = Post.all.order("created_at DESC").limit(5)
  end

  def subcategory_icon(id)
    subcategory = Subcategory.find(id)
    if subcategory.icon && subcategory.icon != nil
      subcategory.icon.to_s
    else
      'icons/code-icon.svg'
    end
  end
end

app/views/posts/_author.html.erb
<div class="author">
	<% if @author.photo != '' && @author.photo != nil %>
	  <%= image_tag @author.photo, class: 'author-photo' %>
	<% else %>
	<% end %>
</div>
<div class="author author-info"> 
	autor: <%= link_to @author.name, @author, class: 'author-name' %><br>
	em: <%= @post.created_at.strftime("%d / %m / %Y") %>
</div>

app/views/posts/_comments.html.erb
<h2>Comentários</h2>

<%= render 'comments/form', comment: @comment, post: @post %>

<% if @post_comments.any? %>
  <table>
    <thead>
      <tr>
        <th>Author</th>
        <th>Comment body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @post_comments.each do |comment| %>
        <tr>
          <td><%= comment.author %></td>
          <td><%= comment.comment_body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  Sem comentários ainda. Seja o primeiro a comentar!
<% end %>

app/views/posts/_form.html.erb
<div class="post-form">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      </br>
      <%= form.text_field :title, id: :post_title, placeholder: 'Título',class: 'post-form-small-field' %>
    </div>

     </br>
      <%= form.label "Author" %>
      </br>
      <%= form.select :author_id, @authors.collect {|a| [a.name, a.id]}, {}, { id: 'select-author', class: 'post-form-small-field' } %>
    </br>

    </br>
      <%= form.label "Category" %>
      </br>
      <%= form.select :category_id, @categories.collect {|c| [c.name, c.id]}, {}, { id: 'select-category', class: 'post-form-small-field' } %>
    </br>

    </br>
      <%= form.label "Subcategory" %>
      </br>
      <%= form.select :subcategory_id, @subcategories.collect {|s| [s.name, s.id]}, {}, { class: 'post-form-small-field' } %>
    </br>
    </br>

    <div class="field">
      <%= form.label :front_image %>
      </br>
      <%= form.text_field :front_image, id: :post_front_image, placeholder: '279px (largura/width) x 159 px(altura/width)', class: 'post-form-small-field' %>
    </div>
    </br>

    <div class="field">
      <%= form.label :image_name %>
      </br>
      <%= form.text_field :image_name, id: :post_image_name, placeholder: 'Nome da imagem', class: 'post-form-small-field' %>
    </div>
    </br>

    <div class="field">
      <%= form.label :url %>
      </br>
      <%= form.text_field :url, id: :post_url, placeholder: 'URL', class: 'post-form-small-field' %>
    </div>
    </br>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, id: :post_body, value: @body_value, class: 'post-form-body' %>
    </div>
    </br>

    <div class="field">
      <%= form.label :intro_text %>
      <%= form.text_area :intro_text, id: :post_intro_text, placeholder: 'Texto de introdução', class: 'post-form-intro-body' %>
    </div>
    </br>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $("#select-category").change(function() {
    let id_value = $("#select-category").val();
    console.log("valor do select = " + id_value);
  });
</script>

app/views/posts/_posts_all.html.erb
<div class="search-bar-container">
	<%= form_for(:current_search, url: search_posts_path) do |f|%>
		<%= f.text_field :search, placeholder: "Buscar Posts", class: 'search-bar' %>
		<%= button_tag(type: "submit", class: 'search-bar-button') do %>
			<i class="fa fa-search fa-lg"></i>
		<% end %>
	<% end %>
</div>
<div class="posts-all-container">
	<div class="posts-all-subcontainer">
		<% @posts.each do |post| %>
			<div class="single-post">
				<h3 class="posts-all-title-mobile"> <%= link_to post.title, post_path(post), class: 'posts-all-title' %> </h3>
				<% if post.front_image != '' && post.front_image != nil %>
					<%= image_tag post.front_image, alt: post.image_name, title: post.image_name,class: 'post-front-image' %>
				<% else %> 
				<% end %>
				<div class="posts-all-intro">
					<div class="post-date"><%= post.created_at.strftime("%d/%m/%Y") %></div>
					<%= link_to post.intro_text, post_path(post), class: 'posts-all-intro' %> <%= link_to "Leia mais ...", post_path(post), class: 'post-categories-name' %> 
					<div class="posts-all-visits"> Visitas: <%= post.visits %> </div>
				</div>
		    <% if logged_in? %>
		      <%= link_to 'Edit', edit_post_path(post) %>
		      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
		    <% end %>
			</div>
		<% end %>
	</div>
	<div class="post-right-bar">
		<div class="right-bar-categories">
			<h4> CATEGORIAS </h4>
			<% @categories.each do |category| %>
				<%= link_to category.name, subcategories_show_all_path(category), class: 'post-categories-name' %>
				<br>
			<% end %>
		</div>
		<div class="posts-most-views">
			<h4> MAIS VISTOS </h4>
			<% @posts_most_views.each do |post_views| %>
				<%= link_to post_views.title, post_path(post_views), class: 'post-views-title' %>
				<br>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form', post: @post %>
<br>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="posts-index-title">Posts mais recentes</h1>

<% if logged_in? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

<br>

<%= render 'posts_all' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<br>

<%= link_to 'Back', posts_path %>

app/views/posts/search_posts.html.erb
<% if @posts.present? %>
	<h1> Posts encontrados </h1>
	<%= render 'posts_all' %>
<% else %>
	<h1> Nenhum post encontrado </h1>		
<% end %>

app/views/posts/show.html.erb
<head>
	<meta name="description" content="<%= @post.intro_text %>">
</head>
<p id="notice"><%= notice %></p>
<h1 class="post-title"> <%= @post.title %> </h1>
<div class="post-info">
	<div class="subinfo post-author">
		<%= render 'author' %>
	</div>
	<div class="subinfo post-categories">
		<div class="post-category">
			Categoria: <%= link_to @category.name, subcategories_show_all_path(@category), class: 'author-name' %>
		</div>
		<div class="post-subcategory">
			Subcategoria: <%= link_to @subcategory.name, sub_posts_path(@subcategory), class: 'author-name' %>
		</div>
	</div>
</div>
<div class="post-body-container">
	<div class="side post-body">
		<%= raw @post.body %>
		<div class="post-body-comments">
			<h2 class="post-commets-title"> Comentários </h2>
			<div id="fb-root"></div>
			<div class="fb-comments" data-href="http://www.aprendesim.com/posts/<%=@post.url%>" data-numposts="5" data-width="100%"></div>
		</div>
	</div>
	<div class="side post-right-bar">
		<div class="right-bar-categories">
			<h4> CATEGORIAS </h4>
			<% @categories.each do |category| %>
				<%= link_to category.name, subcategories_show_all_path(category), class: 'post-categories-name' %>
				<br>
			<% end %>
		</div>
		<div class="posts-most-views">
			<h4> MAIS VISTOS </h4>
			<% @posts_most_views.each do |post_views| %>
				<%= link_to post_views.title, post_path(post_views), class: 'post-views-title' %>
				<br>
			<% end %>
		</div>
	</div>
</div>
<% if logged_in? %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>
<% end %>
<br>